### ISSUE TITLE
Error: Is a directory (os error 21)

### ISSUE THREAD

**Issue by zztkm** [MICKeyzwo/minecraft-log-forwarder#5]
実行ログ

```shell
❯ /home/zztkm/.deno/bin/deno run --allow-read --allow-net /home/zztkm/genkai-mc-server/logForwarder.ts /home/zztkm/genkai-mc-server/log_forwarder_config.json
error: Uncaught (in promise) Error: Is a directory (os error 21)
    const fileContent = await Deno.readTextFile(config.logFilePath);
                        ^
    at async Object.readTextFile (deno:runtime/js/40_read_file.js:55:20)
    at async file:///home/zztkm/genkai-mc-server/logForwarder.ts:22:25
```

**Comment by zztkm** [comment]
ごめん、設定ミス

**Comment by zztkm** [comment]
```json
    "logFilePath": "./logs",  // マイクラのログファイル（latest.log）のパス
```

こっちの方がいいな
```json
    "logFilePath": "./logs/latest.log",  // マイクラのログファイル（latest.log）のパス
```
